/*******************************************************************************
 * File generated from the petstore-app::org::agoncal::application::petstore::domain::Address uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 04. September 2015 09:24:23 MESZ
 *******************************************************************************/
package org.agoncal.application.petstore.domain;

import com.googlecode.objectify.annotation.Embed;
import java.util.ArrayList;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of Address.
 * 
 * @author 
 */
@Embed
public class Address {
	/**
	 * Description of the property street1.
	 */
	
	public String
	 street1
	;
	/**
	 * Description of the property city.
	 */
	
	public String
	 city
	;
	/**
	 * Description of the property zipcode.
	 */
	
	public String
	 zipcode
	;
	/**
	 * Description of the property country.
	 */
	
	public String
	 country
	;
	// Start of user code (user defined attributes for Address)
	
	// End of user code
	
	/**
	 * The default constructor.
	 */
	public Address() {
		
	}
	
	/**
	 * Description of the method getStreet1.
	 * @return 
	 */
	
	public String
	 getStreet1() {
		return this.street1;
	}
	 
	/**
	 * Description of the method getCity.
	 * @return 
	 */
	
	public String
	 getCity() {
		return this.city;
	}
	 
	/**
	 * Description of the method getZipcode.
	 * @return 
	 */
	
	public String
	 getZipcode() {
		return this.zipcode;
	}
	 
	/**
	 * Description of the method getCountry.
	 * @return 
	 */
	
	public String
	 getCountry() {
		return this.country;
	}
	 
	/**
	 * Description of the method setStreet1.
	 * @param street1 
	 */
	
	public void
	 setStreet1( String street1) {
		this.street1 = street1;
	}
	 
	/**
	 * Description of the method setCity.
	 * @param city 
	 */
	
	public void
	 setCity( String city) {
		this.city = city;
	}
	 
	/**
	 * Description of the method setZipcode.
	 * @param zipcode 
	 */
	
	public void
	 setZipcode( String zipcode) {
		this.zipcode = zipcode;
	}
	 
	/**
	 * Description of the method setCountry.
	 * @param country 
	 */
	
	public void
	 setCountry( String country) {
		this.country = country;
	}
	 
	// Start of user code (user defined methods for Address)
	
	// End of user code
	

	

	

	



}
