/*******************************************************************************
 * File generated from the petstore-app::org::agoncal::application::petstore::domain::Item uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 04. September 2015 09:24:22 MESZ
 *******************************************************************************/
package org.agoncal.application.petstore.domain;

import com.googlecode.objectify.annotation.Id;
import com.googlecode.objectify.annotation.Entity;
import com.googlecode.objectify.Ref;
import java.lang.Long;
import java.util.ArrayList;
import org.agoncal.application.petstore.domain.Product;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of Item.
 * 
 * @author 
 */
@Entity
public class Item {
	/**
	 * Description of the property id.
	 */
	@Id
	private Long
	 id
	;
	/**
	 * Description of the property name.
	 */
	
	private String
	 name
	;
	/**
	 * Description of the property description.
	 */
	
	private String
	 description
	;
	/**
	 * Description of the property unitCost.
	 */
	
	private float
	 unitCost
	;
	/**
	 * Description of the property product.
	 */
	
	public 
	Ref<Product>
	
	 product
	;
	// Start of user code (user defined attributes for Item)
	
	// End of user code
	
	/**
	 * The default constructor.
	 */
	public Item() {
		
	}
	
	/**
	 * Description of the method getId.
	 * @return 
	 */
	
	public long
	 getId() {
		return this.id;
	}
	 
	/**
	 * Description of the method getName.
	 * @return 
	 */
	
	public String
	 getName() {
		return this.name;
	}
	 
	/**
	 * Description of the method getDescription.
	 * @return 
	 */
	
	public String
	 getDescription() {
		return this.description;
	}
	 
	/**
	 * Description of the method getUnitCost.
	 * @return 
	 */
	
	public float
	 getUnitCost() {
		return this.unitCost;
	}
	 
	/**
	 * Description of the method getProduct.
	 * @return 
	 */
	
	public Product
	 getProduct() {
		return this.product.get();
	}
	 
	/**
	 * Description of the method setId.
	 * @param id 
	 */
	
	public void
	 setId( long id) {
		this.id = id;
	}
	 
	/**
	 * Description of the method setName.
	 * @param name 
	 */
	
	public void
	 setName( String name) {
		this.name = name;
	}
	 
	/**
	 * Description of the method setDescription.
	 * @param description 
	 */
	
	public void
	 setDescription( String description) {
		this.description = description;
	}
	 
	/**
	 * Description of the method setUnitCost.
	 * @param unitCost 
	 */
	
	public void
	 setUnitCost( float unitCost) {
		this.unitCost = unitCost;
	}
	 
	/**
	 * Description of the method setProduct.
	 * @param product 
	 */
	
	public void
	 setProduct( Product product) {
		this.product = Ref.create(product);
	}
	 
	// Start of user code (user defined methods for Item)
	
	// End of user code
	

	

	

	

	



}
