/*******************************************************************************
 * File generated from the petstore-app::org::agoncal::application::petstore::domain::CreditCard uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 04. September 2015 10:00:12 MESZ
 *******************************************************************************/
package org.agoncal.application.petstore.domain;

import com.googlecode.objectify.annotation.Embed;
import java.util.ArrayList;
import org.agoncal.application.petstore.domain.CreditCardType;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of CreditCard.
 * 
 * @author 
 */
@Embed
public class CreditCard {
	/**
	 * Description of the property creditCardNumber.
	 */
	
	private String
	 creditCardNumber
	;
	/**
	 * Description of the property creditCardType.
	 */
	
	private CreditCardType
	 creditCardType
	;
	/**
	 * Description of the property creditCardExpDate.
	 */
	
	private String
	 creditCardExpDate
	;
	// Start of user code (user defined attributes for CreditCard)
	
	// End of user code
	
	/**
	 * The default constructor.
	 */
	public CreditCard() {
		
	}
	
	/**
	 * Description of the method getCreditCardNumber.
	 * @return 
	 */
	
	public String
	 getCreditCardNumber() {
		return this.creditCardNumber;
	}
	 
	/**
	 * Description of the method getCreditCardType.
	 * @return 
	 */
	
	public CreditCardType
	 getCreditCardType() {
		return this.creditCardType;
	}
	 
	/**
	 * Description of the method getCreditCardExpDate.
	 * @return 
	 */
	
	public String
	 getCreditCardExpDate() {
		return this.creditCardExpDate;
	}
	 
	/**
	 * Description of the method setCreditCardNumber.
	 * @param creditCardNumber 
	 */
	
	public void
	 setCreditCardNumber( String creditCardNumber) {
		this.creditCardNumber = creditCardNumber;
	}
	 
	/**
	 * Description of the method setCreditCardType.
	 * @param creditCardType 
	 */
	
	public void
	 setCreditCardType( CreditCardType creditCardType) {
		this.creditCardType = creditCardType;
	}
	 
	/**
	 * Description of the method setCreditCardExpDate.
	 * @param creditCardExpDate 
	 */
	
	public void
	 setCreditCardExpDate( String creditCardExpDate) {
		this.creditCardExpDate = creditCardExpDate;
	}
	 
	// Start of user code (user defined methods for CreditCard)
	
	// End of user code
	

	

	



}
